### ISSUE TITLE
Error in center of mass calculation lengthOverBreadth  (v 1.4.6)

### ISSUE THREAD

**Issue by ProzacR** [rajarshi/cdkdescui#1]
Lets grab sdf from here:
http://molsync.com/demo/greensolvents.php
And calculate everything for it. We will get error:
"Serial Number Title Exception Message Descriptor
1 Error in center of mass calculation lengthOverBreadth
2 Error in center of mass calculation lengthOverBreadth
...."
Same happens with other sdf I tested too.
On windows 7 two machines.

**Comment by rajarshi** [comment]
This occurs because the molecule is flat and is not considered 3D

**Comment by thegodone** [comment]
I have the same issue and molecules are 3D, look like the lengthOverBreadth call get3DCentreOfMass (input need to be 2D molecule) instead of get3Dcenter (input need to be 3D molecule).

**Comment by rajarshi** [comment]
For the molecules available via the link in the original post, they are all flat and do not have 3D coordinates.

The use of get3DCentreOfMass is correct since it computes the 3D CoM (the Javadoc is misleading). get3Dcenter  only computes the geometric center of a molecule and not the CoM.

Can you send the SDF of the molecule this is failing on?
